# Copyright 2023 Observational Health Data Sciences and Informatics
#
# This file is part of ConcurrentComparator
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Create an outcome model, and compute the relative risk
#'
#' @details
#' For likelihood profiling, either specify the `profileGrid` for a completely user- defined grid, or
#' `profileBounds` for an adaptive grid. Both should be defined on the log effect size scale. When both
#' `profileGrid` and `profileGrid` are `NULL` likelihood profiling is disabled.
#'
#' @description
#' Create an outcome model, and computes the relative risk
#'
#' @param population            A population object generated by [createStudyPopulation()],
#'                              potentially filtered by other functions.
#' @param modelType             The type of outcome model that will be used. TODO
#' @param profileGrid           A one-dimensional grid of points on the log(relative risk) scale where
#'                              the likelihood for coefficient of variables is sampled. See details.
#' @param profileBounds         The bounds (on the log relative risk scale) for the adaptive sampling
#'                              of the likelihood function. See details.
#' @param prior                 The prior used to fit the model. See [Cyclops::createPrior()]
#'                              for details.
#' @param control               The control object used to control the cross-validation used to
#'                              determine the hyper-parameters of the prior (if applicable). See
#'                              [Cyclops::createControl()] for details.
#'
#' @return
#' An object of class `OutcomeModel`. Generic function `print`, `coef`, and
#' `confint` are available.
#'
#' @export
fitOutcomeModel <- function(population,
                            modelType = "cpr",
                            profileGrid = NULL,
                            profileBounds = c(log(0.1), log(10)),
                            prior = createPrior("laplace", useCrossValidation = TRUE),
                            control = createControl(
                                cvType = "auto",
                                seed = 1,
                                resetCoefficients = TRUE,
                                startingVariance = 0.01,
                                tolerance = 2e-07,
                                cvRepetitions = 10,
                                noiseLevel = "quiet"
                            )) {
    errorMessages <- checkmate::makeAssertCollection()
    checkmate::assertDataFrame(population, null.ok = TRUE, add = errorMessages)
    checkmate::assertChoice(modelType, c("cpr", "poisson", "cox"), add = errorMessages)
    checkmate::assertNumeric(profileGrid, null.ok = TRUE, add = errorMessages)
    checkmate::assertNumeric(profileBounds, null.ok = TRUE, len = 2, add = errorMessages)
    checkmate::assertClass(prior, "cyclopsPrior", add = errorMessages)
    checkmate::assertClass(control, "cyclopsControl", add = errorMessages)
    checkmate::reportAssertions(collection = errorMessages)

    return(NULL)
}

#' Create a study population
#'
#' @details
#' TODO
#'
#' @template ConcurrentComparatorData
#'
#' @param outcomeId                        The ID of the outcome.
#' @return
#' A `tibble` specifying the study population. This `tibble` will have the following columns:
#'
#' - `rowId`: A unique identifier for an exposure.
#' - `personSeqId`: The person sequence ID of the subject.
#' - `cohortStartdate`: The index date.
#' - `outcomeCount` The number of outcomes observed during the risk window.
#' - `timeAtRisk`: The number of days in the risk window.
#' - `survivalTime`: The number of days until either the outcome or the end of the risk window.
#'
#' @export
createStudyPopulation <- function(ConcurrentComparatorData,
                                  outcomeId) {
    errorMessages <- checkmate::makeAssertCollection()
    checkmate::assertClass(concurrentComparatorData, "concurrentComparatorData", add = errorMessages)
    checkmate::assertInt(outcomeId, len = 1, add = errorMessages)
    checkmate::reportAssertions(collection = errorMessages)

    return(NULL)
}

